[package]
name = "objr"
version = "0.2.0"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html